Parse or throw
servacc/CVSCommon pull request #10
Opened 2021-07-14 01:26 UTC by efimov-evgeniy

Добавил методы `parse_or_throw()` и `getArray()` для `Config`

2021-07-20 06:26 UTC, ssysoenko requested changes
Не думаю, что плодить методы с исключениями и без имеет смысл. Гораздо локаничнее и удобнее будет использовать `expected` (точнее его бустовый аналог).

2021-07-20 06:26 UTC, ssysoenko commented on include/cvs/common/config.hpp
> +  [[nodiscard]] std::optional<std::vector<Config> > getArray(const std::string &) const;
А что тут с форматированием случилось?

2021-07-20 06:26 UTC, ssysoenko commented on include/cvs/common/config.hpp
> +      throw Exception{fmt::format("Can't parse {} config.{}", Config_parser::get_name(),
Это, конечно, полезнее чем бэд опшинал, но вот совсем непонятно что пошло не так. Можно у буста узнать про неправильный синтаксис, а у конфигуратора не указанное значение для обязательного поля?

2021-07-22 00:46 UTC, efimov-evgeniy commented on include/cvs/common/config.hpp
> +      throw Exception{fmt::format("Can't parse {} config.{}", Config_parser::get_name(),
У буста можно узнать номер строки с ошибкой. В конфиге тоже можно в теории получить непосредственную проблему, но вопрос в том, как это возвращать. Либо `expected` или аналог, либо логирование прямо на месте.

2021-07-22 01:16 UTC, efimov-evgeniy commented
> Не думаю, что плодить методы с исключениями и без имеет смысл. Гораздо локаничнее и удобнее будет использовать `expected` (точнее его бустовый аналог).

Так всё равно придётся делать функцию, которая бросает исключение. Ну или будут те же самые проверки

2021-08-09 15:58 UTC, ssysoenko commented
> > Не думаю, что плодить методы с исключениями и без имеет смысл. Гораздо локаничнее и удобнее будет использовать `expected` (точнее его бустовый аналог).
> 
> Так всё равно придётся делать функцию, которая бросает исключение. Ну или будут те же самые проверки

Не нужно методов бросающих исключения. Был метод который возвращает значение или признак ошибки. Нужно чтобы возвращалось значение или ошибка. Если код способен ошибку обработать - выполняются проверки и т.д. Если код ошибку не может обработать - ошибка передается выше. И тут уже варианты для пользователя: 
- не писать никаких проверок, просто попробовать взять значение, что закончится исключением которое уже будет ловить код выше
- проверить есть ли ошибка, вернуть ошибу через return/out
- сделать вложенное исключение

2021-08-30 15:46 UTC, closed without merging