Обновление конфига
servacc/CVSCommon pull request #11
Opened 2021-08-11 19:27 UTC by ssysoenko

Попытка сделать код читабильнее сохранив идею.
Информация для распарса сознательно теперь не в типах (создаются `FieldDescriptor` и сохраняются в контейнер, есть виртуальные вызовы и т.д.). Сделано это чтобы описание конфига выглядело как описание структуры.
При объявлении струкутуры конфига обязательно указывать описание как всего конфига так и всех его полей. Конфиг умеет выдавать свое описание.

TODO:

1. опциональные вложенные струкутры
2. массивы

2021-08-11 20:20 UTC, roman-orekhov commented on include/cvs/common/config.hpp
> +    virtual bool has_dafault() const = 0;
has_d**e**fault

2021-08-11 20:26 UTC, roman-orekhov commented on include/cvs/common/config.hpp
> +      return prefix.data() + fmt::format(BaseFieldDescriptor::description_format, field_name_str, field_base_type_str,
Не эффективно (хотя важно ли это тут?). Можно в description_format спереди добавить {}, и в него уже пихать prefix.

2021-08-11 20:32 UTC, roman-orekhov commented on include/cvs/common/config.hpp
> +          config.*pointer = T::make(boost::property_tree::ptree{}).value();
То есть дефолтные значения для типа предопределены? Для чисел -- ноль, для строк -- пустая...

2021-08-11 20:48 UTC, roman-orekhov commented on src/config.cpp
> +  ss << content;
Есть конструктор для этого.

2021-08-11 21:09 UTC, roman-orekhov approved these changes
Печаль, конечно, что очередной конфиг пишется на ptree. Хотелось бы уже какую-нибудь либу, умеющую различать true от "true". (Кстати, полезно иметь тест на bool, да и на string, раз уж на то пошло). Иная либа также могла бы помочь с сериализацией (полезно для передачи заказчику дефолтных настроек).

В целом для решения на макросах выглядит норм :)
Отмечу только, что слишком много сложений строк для проекта, где уже используется fmtlib, и можно использовать fmt::format и fmt::join везде.
Также я бы сократил `params.value()` до `params()`, а то слишком неудобно пользоваться будет.

2021-08-11 21:54 UTC, ssysoenko commented on include/cvs/common/config.hpp
> +          config.*pointer = T::make(boost::property_tree::ptree{}).value();
Выше проверяются вложенные поля. Если все поля с типами default и optional - то в конфиге может отсутствовать кусок для этой вложенной струкутуры и ее можно проинитить пустым деревом.

2021-08-11 22:06 UTC, ssysoenko commented
> Печаль, конечно, что очередной конфиг пишется на ptree. Хотелось бы уже какую-нибудь либу, умеющую различать true от "true". 

За буст то, что это буст и все его знают и всюду он есть. В части json мне нравится [эта](https://github.com/nlohmann/json) либа. Но нравится она мне исключительно по описанию. Использовать ее мне не довелось. Думаю загнать под условную компиляцию разынуе либы для json.

> (Кстати, полезно иметь тест на bool, да и на string, раз уж на то пошло). Иная либа также могла бы помочь с сериализацией (полезно для передачи заказчику дефолтных настроек).
 
 Учту.
 
> Отмечу только, что слишком много сложений строк для проекта, где уже используется fmtlib, и можно использовать fmt::format и fmt::join везде.

Ну это я просто утомился и поспешил выложить. :)

> Также я бы сократил `params.value()` до `params()`, а то слишком неудобно пользоваться будет.

Тут та же история, что и с json - уже есть буст и чо дергаться. Альтернатива [вот](https://github.com/TartanLlama/expected). Ну а вообще вроде подобное должно появиться в std.

2021-08-12 00:54 UTC, efimov-evgeniy approved these changes

2021-08-12 00:54 UTC, efimov-evgeniy commented on include/cvs/common/config.hpp
> +  static constexpr const char* name##_description = description; \
А зачем тут глобальные переменные? Передай имя как аргумент шаблона

2021-08-12 00:54 UTC, efimov-evgeniy commented on include/cvs/common/config.hpp
> +  template <typename T,
Есть смысл делать отдельный класс под дефолтное значение? Можно же просто в шаблон булеву переменную прокинуть. Или сделать перечисление и соединить ещё и optional

2021-08-12 00:54 UTC, efimov-evgeniy commented on test/configtest.cpp
> +CVS_CONFIG(TestConfig, "Test config") {
Фигурные скобки так важны? Без них можно было бы сделать всё на типах.
Возможно, получится сделать и с фигурными. Я даже примерно знаю как.

2021-08-12 00:56 UTC, efimov-evgeniy requested changes
Хотелось бы использовать типы

2021-08-12 08:09 UTC, ssysoenko commented on include/cvs/common/config.hpp
> +  static constexpr const char* name##_description = description; \
Я не проверял и прибывал в уверенности, что строковый литерал как он есть в шаблон не влазит.

2021-08-12 08:13 UTC, ssysoenko commented on include/cvs/common/config.hpp
> +  template <typename T,
Да. Именно так переписать и нужно.

2021-08-12 08:34 UTC, ssysoenko commented on test/configtest.cpp
> +CVS_CONFIG(TestConfig, "Test config") {
Тут сознательно пожертвовано правильными вещами (дескрипторы только типами без выделения памяти, сначала распарс потом создание и инициализация структуры конфига) чтобы выглядело краше (правда это субъективщина). Но вроде как не все так плохо: большого перерасхода памяти нет (пара указателей +/-), виртуальные взовы тоже на производительность не влияют, ну сами струкутуры не имеют сложной инициализации поэтому парсинг -> создание и инициализация - оно каэшн по книжке и правильно, но в данном случае ничего не дает.
В целом да, можно только на типах, но без `{}`.

2021-08-12 10:17 UTC, efimov-evgeniy commented on include/cvs/common/config.hpp
> +  static constexpr const char* name##_description = description; \
Если не лезть в с++2a, можно вот так: https://github.com/Centimo/Meta_lib/blob/master/Constexpr_string.hpp

2021-08-12 12:24 UTC, ssysoenko commented
> Хотелось бы использовать типы

Зачем?

2021-08-12 12:58 UTC, roman-orekhov commented on include/cvs/common/config.hpp
> +          config.*pointer = T::make(boost::property_tree::ptree{}).value();
Я считаю нужным дефолт для вложенного определять индивидуально. Пример в Азимуте был: была структура, определяющая параметры для сохранения картинок в ImageSaver. По дефолту выбрано было jpg с параметрами в виде массива [1,100] (так в opencv кодируется 100% качество в jpg). Ясное дело, что для другого случая имеет смысл другой дефолт (png с другим массивом, который определяет степень сжатия).

2021-08-12 17:18 UTC, ssysoenko commented on include/cvs/common/config.hpp
> +          config.*pointer = T::make(boost::property_tree::ptree{}).value();
Надеюсь правильно тебя понял: ты пишешь о том, чтобы дефолты для вложенных струкутур определять так же как и для обычных полей:
`CVS_FIELD_DEFAULT(nested, NestedConfig, {some_values, bla, bla, bla},  "Comment");`
?
В том виде как написано сейчас такое, похоже, не получится. Надо возвращаться к старому варианту где поля перечисляются внутри макроса. Когда поля  - аргументы макроса мне не нравится эстетически.

2021-08-12 18:10 UTC, ssysoenko commented on include/cvs/common/config.hpp
> +  static constexpr const char* name##_description = description; \
Я смотрю примеры применения и всюду нельзя напрямую в шаблон строковый литерал запихать.

2021-08-12 23:24 UTC, efimov-evgeniy commented on test/configtest.cpp
> +CVS_CONFIG(TestConfig, "Test config") {
Просто фигурные скобки мне кажутся не особо полезными (и даже чуть-чуть вредными), а вот ошибки на этапе компиляции я очень люблю

2021-08-12 23:28 UTC, efimov-evgeniy commented on include/cvs/common/config.hpp
> +  static constexpr const char* name##_description = description; \
Если использовать код по ссылке, то делается так:
`SomeClass<decltype(get_constexpr_string([]() {return "literal"; }))>`
Соответственно, `decltype(get_constexpr_string([]() {return "literal"; }))` можно запихнуть в макрос.

2021-08-13 01:18 UTC, roman-orekhov commented on include/cvs/common/config.hpp
> +  static constexpr const char* name##_description = description; \
Ну то есть снова макрос будет, и тогда в чём разница?

2021-08-13 01:20 UTC, roman-orekhov commented on include/cvs/common/config.hpp
> +          config.*pointer = T::make(boost::property_tree::ptree{}).value();
Не обязательно так, можно требовать создать переменную вне макроса, и уже её передавать по имени. В конце концов, ровно этот дефолт может не в одном месте быть нужен.

2021-08-13 10:14 UTC, efimov-evgeniy commented on include/cvs/common/config.hpp
> +  static constexpr const char* name##_description = description; \
Разница с чем? С тем, что сейчас есть в этом ПР в том, что не будет лишних сущностей в глобальной области видимости.

2021-08-13 10:17 UTC, efimov-evgeniy commented on include/cvs/common/config.hpp
> +          config.*pointer = T::make(boost::property_tree::ptree{}).value();
А дефолты для отдельных полей и для всей структуры как будут взаимодействовать?

2021-08-14 20:17 UTC, ssysoenko commented on test/configtest.cpp
> +CVS_CONFIG(TestConfig, "Test config") {
> фигурные скобки мне кажутся не особо полезными (и даже чуть-чуть вредными)

Почему вредные?

> а вот ошибки на этапе компиляции я очень люблю

дык строгая типизация никуда не делась. Просто теперь не тайпдеф на тапл описывает все поля, а есть константы с дескрипторами и вектор указателей на эти константы.

2021-08-15 01:34 UTC, roman-orekhov commented on test/configtest.cpp
> +  };
Текст не соответствует описанию

2021-08-15 01:41 UTC, roman-orekhov commented on include/cvs/common/config.hpp
> +  static constexpr const char* name##_description = description;                                   \
Зачем это оставлено, если ты-таки решил заюзать constexprString? Казалось бы только для целей избавиться от мусорных констант

2021-08-30 15:25 UTC, Aldrog approved these changes

2021-08-30 15:41 UTC, efimov-evgeniy approved these changes

2021-08-30 15:46 UTC, merged