Feature/logger
servacc/CVSCommon pull request #13
Opened 2021-09-11 09:31 UTC by ssysoenko

Добавлен логгер из CVSLogger. 
Рефакторинг логгера.
Фабрики возвращают результат в `CVSOutcome`.

2021-09-12 23:14 UTC, efimov-evgeniy requested changes

2021-09-12 23:14 UTC, efimov-evgeniy commented on logger/include/cvs/logger/opencvHelper.hpp
> +      save_path = save_path / logger->name() / spdlog::level::to_short_c_str(lvl);
А почему тут тоже не использовать `/=`?

2021-09-12 23:14 UTC, efimov-evgeniy commented on logger/src/logging.cpp
> +        auto cfg = LoggerConfig::make(l.second);
Переменная `cfg` не используется?

2021-09-12 23:14 UTC, efimov-evgeniy commented on logger/src/logging.cpp
> +        configurations(cfg_struct_opt->name) = cfg;
Может, как-то переименовать функцию? Разделить на константную `at` и записывающую `set`? Имхо присвоение вызову функции - не самая очевидная механика.

2021-09-12 23:14 UTC, efimov-evgeniy commented on logger/src/tools/fpsLogger.cpp
> +    update_mutex.lock();
Если сделать `std::optional<std::shared_lock>` (к примеру), можно будет проверять один раз и использовать RAII. И вместо `update_mutex` + `use_lock` можно использовать `std::optional<std::shared_mutex>`.

2021-09-13 05:32 UTC, ssysoenko commented on logger/src/logging.cpp
> +        configurations(cfg_struct_opt->name) = cfg;
В функции `static` переменная. С глобальными и т.п. переменными были какие-то проблемы (не сейчас, а раньше и я уже забыл что конкретно и пишу по инерции).

2021-09-13 05:50 UTC, ssysoenko commented on logger/include/cvs/logger/opencvHelper.hpp
> +      save_path = save_path / logger->name() / spdlog::level::to_short_c_str(lvl);
Потому, что `logger->name() / spdlog::level::to_short_c_str(lvl);` не работатет.

2021-09-13 06:16 UTC, ssysoenko commented on logger/src/tools/fpsLogger.cpp
> +    update_mutex.lock();
Мьюткс копировать нельзя.

2021-09-13 10:28 UTC, efimov-evgeniy commented on logger/src/logging.cpp
> +        configurations(cfg_struct_opt->name) = cfg;
Не понял про глобальные переменные. Я о функции исключительно. Сделать что-то вроде `static const Configuration& at(std::string name)` и `static void/bool set(std::string name, Configuration new_configuration)`

2021-09-13 10:33 UTC, efimov-evgeniy commented on logger/src/tools/fpsLogger.cpp
> +    update_mutex.lock();
Так в моём предложении и нет копирования, вроде бы.

2021-09-13 10:52 UTC, ssysoenko commented on logger/src/logging.cpp
> +        configurations(cfg_struct_opt->name) = cfg;
Идея сделать глобальную мапу с настройками логера. Нужно чтобы можно было сохранять дерево настроек для конкретного логера и потом использовать их в `argumentPreprocessor`. Это перерасход ресурсов, но нет ограничения, что необходимо для каждой специализации `argumentPreprocessor` дергать свой `initLogger` (в `initLogger` парсятся и инициализируются базовые параметры логера, а каждый препроцессор, если надо, парсит свои сам в момент вызова).
Можно сделать глобальную переменную и получить проблемы с несколькими экземплярами в момент линковки, или использовать функцию, в которой создается статическаая еперменная и возвращать ссылку на эту переменную (этот подход, на сколько я помню, лишен проблем с несколькими экземплярами). Именно потому как должна быть такая функция - невозможно сделать `at` и `set` (ну или такие функции сделать, но `configurations` никуда не денется).

2021-09-13 10:54 UTC, ssysoenko commented on logger/src/tools/fpsLogger.cpp
> +    update_mutex.lock();
`std::optional` пытается определитиь `operator=(const std::optional&)` и выдает ошибку.

2021-09-13 11:05 UTC, efimov-evgeniy commented on logger/src/tools/fpsLogger.cpp
> +    update_mutex.lock();
Это `std::optional<std::shared_mutex>`? У меня просто так сделано в `modules/ROSModule/Mediator`, и там всё работает.

2021-09-13 11:05 UTC, Aldrog commented on logger/src/tools/fpsLogger.cpp
> +    update_mutex.lock();
https://en.cppreference.com/w/cpp/utility/optional/operator%3D

> Overload (2) is defined as deleted unless std::is_copy_constructible_v<T> and std::is_copy_assignable_v<T> are both true.

Может быть, ты его где-то таки пытаешься скопировать и ошибка на это выдаётся?

2021-09-13 11:06 UTC, efimov-evgeniy commented on logger/src/tools/fpsLogger.cpp
> +    update_mutex.lock();
Вероятно, ты где-то пытаешься вызвать это оператор присваивания.

2021-09-13 11:07 UTC, ssysoenko commented on logger/src/tools/fpsLogger.cpp
> +    update_mutex.lock();
Пытался делать и так и так:
```
std::optional<std::shared_mutex> opt = std::shared_mutex();
std::optional<std::shared_mutex> opt = std::make_optional(std::shared_mutex());
```

2021-09-13 11:12 UTC, efimov-evgeniy commented on logger/src/tools/fpsLogger.cpp
> +    update_mutex.lock();
'std::optional<std::shared_mutex> opt(std::make_optional<std::shared_mutex>());'

2021-09-13 11:15 UTC, Aldrog commented on logger/src/tools/fpsLogger.cpp
> +    update_mutex.lock();
Можно так:
```
std::optional<std::shared_mutex> opt{std::in_place};
```
Вот перезаписать этот `optional` не получится, т.к. мутекс не только не копируется, но даже не перемещается.

2021-09-13 11:16 UTC, ssysoenko commented on logger/src/tools/fpsLogger.cpp
> +    update_mutex.lock();
Короче, не получается.

2021-09-13 11:19 UTC, efimov-evgeniy commented on logger/src/tools/fpsLogger.cpp
> +    update_mutex.lock();
```  std::optional<std::shared_mutex> opt(std::in_place);
  std::optional<std::scoped_lock<std::shared_mutex>> lock;
  if (opt) {
    lock.emplace(*opt);
  }```

2021-09-13 11:21 UTC, Aldrog commented on logger/src/tools/fpsLogger.cpp
> +    update_mutex.lock();
@efimov-evgeniy `setUseLock` ты не реализуешь так.

2021-09-13 11:29 UTC, efimov-evgeniy commented on logger/src/tools/fpsLogger.cpp
> +    update_mutex.lock();
Кстати, да: а зачем это реализовывать? Предполагается, что логгер может переходить от синхронизации и обратно в процессе работы?
RAII лок в любом случае можно реализовать.

2021-09-13 11:32 UTC, efimov-evgeniy requested changes

2021-09-13 11:32 UTC, efimov-evgeniy commented on logger/src/tools/fpsLogger.cpp
> +    update_mutex.lock();
В текущем виде это вообще дедлок потенциальный

2021-10-11 10:24 UTC, efimov-evgeniy requested changes

2021-10-11 10:24 UTC, efimov-evgeniy commented on logger/src/tools/fpsLogger.cpp
> +class FpsLogger<ThreadSafe>::Private {
А что это за конструкция?

2021-10-11 10:24 UTC, efimov-evgeniy commented on logger/src/tools/fpsLogger.cpp
> +  if (!started_) {
Это, вообще говоря, небезопасно. Следует использовать атомарный бул и `compare_exchange...`

2021-10-11 10:24 UTC, efimov-evgeniy commented on logger/src/tools/fpsLogger.cpp
> +  if (total_cnt) {
А почему тут нет никакой синхронизации?

2021-10-11 10:24 UTC, efimov-evgeniy commented on logger/src/tools/fpsLogger.cpp
> +  duration report_period = 10min;
Стоит, наверное, обозначит как `const`, иначе вопросы к синхронизации

2021-10-11 10:24 UTC, efimov-evgeniy commented on logger/src/tools/fpsLogger.cpp
> +  if (total_dur.count())
Это тоже небезопасно. Между проверкой (которая, кстати говоря, тоже вряд ли атомарна) и вызовом `fps` может вклиниться `clear`, и получится деление на 0.

2021-10-11 10:26 UTC, ssysoenko commented on logger/src/tools/fpsLogger.cpp
> +class FpsLogger<ThreadSafe>::Private {
pimpl

2021-10-19 11:36 UTC, efimov-evgeniy requested changes

2021-10-19 11:36 UTC, efimov-evgeniy commented on logger/src/tools/fpsCounter.cpp
> +      last_frame_time = clock::now();
Опасно. `newFrame` может вызваться после проверки, и `last_frame_time` не успеет установиться

2021-10-19 11:36 UTC, efimov-evgeniy commented on logger/src/tools/fpsCounter.cpp
> +    lock.unlock();
Лучше сделать скоуп ( `{}` ), чем вручную анлочить

2021-10-19 11:36 UTC, efimov-evgeniy commented on logger/src/tools/fpsCounter.cpp
> +      last_frame_time = clock::now();
Я бы вообще предложил остановиться на использовании исключительно 'shared_mutex' для синхронизации и не мучиться. Если хочется производительности, то тут логично было бы использовать аналог RCU.

2021-10-19 11:49 UTC, ssysoenko commented on logger/src/tools/fpsCounter.cpp
> +    lock.unlock();
Чем лучше?

2021-10-19 12:00 UTC, efimov-evgeniy commented on logger/src/tools/fpsCounter.cpp
> +    lock.unlock();
Лучше использовать механизмы RAII - они более очевидны. Будет видно, что у тебя отдельный блок с синхронизацией.

2021-10-19 12:13 UTC, efimov-evgeniy approved these changes

2021-10-25 03:24 UTC, efimov-evgeniy commented on logger/src/tools/fpsCounter.cpp
> +      start_points.pop();
Так и предполагается, что сначала читается конец очереди, а потом удаляется первый элемент?

2021-10-25 17:02 UTC, merged

2021-11-05 13:50 UTC, roman-orekhov commented on logger/include/cvs/logger/loggable.hpp
> +  explicit Loggable(const std::string& name = boost::core::demangle(typeid(T).name())) { log = *createLogger(name); }
Зачем весь Loggable делать шаблоном, если шаблонного у него -- один конструктор, который и можно сделать шаблонным?

2021-11-05 14:31 UTC, roman-orekhov commented on logger/include/cvs/logger/tools/fpsCounter.hpp
> +  using CounterDuration  = CounterClock::duration;
Зачем в типах префикс Counter? К ним всё равно доступ через IFPSCounter:: будет. Если в типе префикс другого типа, это C-style, и в целом же решается через :: в C++...

2021-11-05 14:34 UTC, roman-orekhov commented on logger/include/cvs/logger/tools/fpsCounter.hpp
> +  virtual double statistics() const = 0;
После рефакторинга пропала та единственная фича, ради которой я и затевал частичную thread-safety изначально, -- возможность забрать текущую статистику по запросу "со стороны" через вызов метода.

2021-11-06 10:38 UTC, ssysoenko commented on logger/include/cvs/logger/loggable.hpp
> +  explicit Loggable(const std::string& name = boost::core::demangle(typeid(T).name())) { log = *createLogger(name); }
Тогда придется каждый раз вызывать конструктор чтобы получить имя логера. А так можно воспользоваться дефортным именем.

2021-11-06 10:39 UTC, ssysoenko commented on logger/include/cvs/logger/tools/fpsCounter.hpp
> +  using CounterDuration  = CounterClock::duration;
Это не задумка, просто так получилось в процессе.

2021-11-06 10:43 UTC, ssysoenko commented on logger/include/cvs/logger/tools/fpsCounter.hpp
> +  virtual double statistics() const = 0;
Да. Это не досмотрели

2021-11-06 11:48 UTC, roman-orekhov commented on logger/include/cvs/logger/loggable.hpp
> +  explicit Loggable(const std::string& name = boost::core::demangle(typeid(T).name())) { log = *createLogger(name); }
Не понял вообще. Если есть объект уже, то у него геттер на имя должен быть. Если нет, то зачем тебе имя логгера, когда он не создан ещё? Можешь кодом описать недоступный в предлагаемом варианте use case?

2021-11-06 14:23 UTC, ssysoenko commented on logger/include/cvs/logger/loggable.hpp
> +  explicit Loggable(const std::string& name = boost::core::demangle(typeid(T).name())) { log = *createLogger(name); }
Возможно я совсем не понял предлагаемый use case. Шаблон сделан чтобы можно было избежать определения конструктора только для того чтобы задать имя логера, особенно когда имя логера вообще не важно, а важно чтоб он просто был. Я не понимаю откуда возьмется имя логера если убрать шаблон? 

От `Loggable` наследуется всякий кто хочет получить именованный логгер. Шаблон нужен только для того, чтобы задать логеру вменяемое имя "автоматически". Если убрать шаблон - придется всякий раз вызывать конструктор руками и передавать в него имя (ну или тип и из него получиать имя). Шаблоный конструктор тоже придется вызывать руками т.к. компилятор для него тип автоматически не выведет.

Думаю нужно добавить вариант реализации, где в шаблон передается сразу имя логера (потипу того как в конфиге коментарии полей задаются) чтобы можно было делать 2мя способами:
1. `class Q : public Loggable<Q>` - тут получаем имя через `boost::core::demangle(typeid(Q).name())`
2. `class Q : public Loggable<CVS_CONSTEXPRSTRING("Qwerty")>` - тут напрямую буквами задаем имя логера

2021-11-06 20:32 UTC, roman-orekhov commented on logger/include/cvs/logger/loggable.hpp
> +  explicit Loggable(const std::string& name = boost::core::demangle(typeid(T).name())) { log = *createLogger(name); }
Понял, о чём речь. Я просто хотел иметь шаблон поменьше. Тогда я бы сделал template<class T> class Loggable : public LoggableImpl с шаблонным конструктором и using второго конструктора, а вся нешаблонная часть легла бы в LoggableImpl