Feature/init
servacc/CVSCommon pull request #2
Opened 2021-03-18 11:59 UTC by ssysoenko

2021-03-18 13:00 UTC, efimov-evgeniy requested changes

2021-03-18 13:00 UTC, efimov-evgeniy commented on include/cvs/common/configbase.hpp
> +  Config_static_type_##name ::ResultType name;                                                                      \
А куда делись постфиксы?

2021-03-18 13:23 UTC, ssysoenko commented on include/cvs/common/configbase.hpp
> +  Config_static_type_##name ::ResultType name;                                                                      \
Канули в небытие. Вообще думал поднять этот вопрос.
Зачем нам постфиксы?

2021-03-18 13:26 UTC, ssysoenko commented on include/cvs/common/configbase.hpp
> +  Config_static_type_##name ::ResultType name;                                                                      \
И конкретно в этом случае задаешь имя ты без постфикса, а получаешь с постфиксом. Это понимается быстро, но все же впечатление портит.

2021-03-18 13:55 UTC, efimov-evgeniy commented on include/cvs/common/configbase.hpp
> +  Config_static_type_##name ::ResultType name;                                                                      \
Я за префиксы, но по текущему стилю у нас постфиксы.

2021-03-18 13:55 UTC, ssysoenko commented on include/cvs/common/configbase.hpp
> +  Config_static_type_##name ::ResultType name;                                                                      \
Чота я в гугл глянул и не нашел там ни префиксов ни постфиксов

2021-03-18 13:56 UTC, efimov-evgeniy commented on include/cvs/common/configbase.hpp
> +  Config_static_type_##name ::ResultType name;                                                                      \
К тому же, ты убрал только в одном месте, а для объектов оставил.

2021-03-18 13:58 UTC, ssysoenko commented on include/cvs/common/configbase.hpp
> +  Config_static_type_##name ::ResultType name;                                                                      \
Ну это я недосмотрел, да

2021-03-18 13:59 UTC, efimov-evgeniy commented on include/cvs/common/configbase.hpp
> +  Config_static_type_##name ::ResultType name;                                                                      \
![image](https://user-images.githubusercontent.com/74912981/111638408-58c11a00-880b-11eb-8346-d63b134cfb1c.png)

2021-03-18 17:30 UTC, ssysoenko commented on include/cvs/common/configbase.hpp
> +  Config_static_type_##name ::ResultType name;                                                                      \
Если бы я это увидел раньше - то оно бы было в гулодоке :)
Таки я бы поднял вопрос о необходимости этой лабуды. Не очень понимаю на кой ляд нужна кастрированная венгерская нотация.

2021-03-22 20:08 UTC, efimov-evgeniy approved these changes

2021-03-23 14:20 UTC, Aldrog requested changes

2021-03-23 14:20 UTC, Aldrog commented on CMakeLists.txt
> +include(GNUInstallDirs)
Генерирует предупреждение:
```
  Unable to determine default CMAKE_INSTALL_LIBDIR directory because no
  target architecture is known.  Please enable at least one language before
  including GNUInstallDirs.
```
Надо сначала объявить `project` и добавить к нему `LANGUAGES CXX`

2021-03-23 14:20 UTC, Aldrog commented on cmake/CVSBuildNumber.cmake
> +endmacro()
Странный скрипт, не очень понятно, как его предполагается использовать.

2021-03-23 14:20 UTC, Aldrog commented on include/cvs/common/configbase.hpp
> +      , Default_value_##name_type, __VA_OPT__(__VA_ARGS__))
Может, всё-таки добавим к этим макросам префикс `CONFIG_`? Кажется, `VALUE` слишком легко может с чем-то ещё пересечься.

2021-03-23 14:20 UTC, Aldrog commented on include/cvs/common/configbase.hpp
> +#define OBJECT(object_name, ...)          HELPER_OBJECT_BASE(object_name, false, __VA_ARGS__)
И здесь тоже лучше бы префикс добавить.

2021-03-23 14:33 UTC, ssysoenko commented on cmake/CVSBuildNumber.cmake
> +endmacro()
Валялся у меня в общей куче и перешел сюда. Предполагается, что номер билдся добавляется только если задан снаружи например 
`cmake -DBUILD_NUMBER=5`
Ниже в проекте делается
`project(A VERSION 1.2.3${BUILD_NUMBER}`
Если параметр отсутствует - номер сборки просто не ставится.

Можно напихать туда хелперов для поддержки номера сборки который мы обсуждали. Но там есть вопросы про автоматизацию.

2021-03-23 14:42 UTC, ssysoenko commented on CMakeLists.txt
> +include(GNUInstallDirs)
А `LANGUAGES CXX` обязательно? Вроде и без него обходится вполне норм.

2021-03-23 15:28 UTC, Aldrog commented on cmake/CVSBuildNumber.cmake
> +endmacro()
Ага, теперь понятно. Может, тогда отдельные переменные для входа и выхода использовать? Например, результат записывать в `VERSION_BUILD_NUMBER`.

2021-03-23 15:33 UTC, Aldrog commented on CMakeLists.txt
> +include(GNUInstallDirs)
Он по умолчанию `C CXX`, так что в целом опционально. Хотя на мой взгляд выключить фичи, связанные с поддержкой C, и добавить большей явности лишним не будет.

2021-03-23 22:53 UTC, efimov-evgeniy commented on include/cvs/common/configbase.hpp
> +      , Default_value_##name_type, __VA_OPT__(__VA_ARGS__))
Имхо тогда лучше какую-то аббревиатуру добавить, типа "CVSC_". Так будет короче и меньше вероятность, что пересечётся.

2021-03-24 10:46 UTC, ssysoenko commented on cmake/CVSBuildNumber.cmake
> +endmacro()
Да я вот думаю а не сделать ли отдельный макрос типа cvsproject. Возможно так еще правильнее будет.

2021-03-24 11:16 UTC, Aldrog commented on cmake/CVSBuildNumber.cmake
> +endmacro()
Да, кажется разумным. И `HOMEPAGE_URL` можно автоматом проставлять.

2021-03-25 07:35 UTC, ssysoenko commented on cmake/CVSBuildNumber.cmake
> +endmacro()
Обертка над `project` выдает предупреждение:
`CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.`

Согласны мы с таким мириться? Причем он так ругается на макрос. Похоже cmake не умеет во вложенность и т.п.

2021-03-25 08:08 UTC, ssysoenko commented on cmake/CVSBuildNumber.cmake
> +endmacro()
Еще можно переопределить `project`. Оно даже работает. Варнинга нет но нативная функция переопределена.

2021-03-25 09:25 UTC, Aldrog commented on cmake/CVSCommon.cmake
> +macro(project)
Я так понимаю, тут есть риск всё сломать, включив CVSCommon дважды. Если вдруг мы всё-таки решим собирать зависимости вместе с проектом, это станет большой проблемой.

2021-03-25 11:38 UTC, Aldrog approved these changes

2021-03-25 11:42 UTC, merged