Version file and factory
servacc/CVSCommon pull request #3
Opened 2021-03-31 06:24 UTC by ssysoenko

2021-03-31 14:37 UTC, efimov-evgeniy requested changes

2021-03-31 14:37 UTC, efimov-evgeniy commented on include/cvs/common/factory.hpp
> +    if (!isRegistered<FactoryFunction>(key)) {
Можно инвертировать.

2021-03-31 14:37 UTC, efimov-evgeniy commented on include/cvs/common/factory.hpp
> +    if (auto key_iter = factory_functions.find(key); key_iter != factory_functions.end()) {
Слишком плотный кусок. Инвертировать и вынести объявления из if'ов

2021-03-31 14:37 UTC, efimov-evgeniy commented on include/cvs/common/factory.hpp
> +      if (auto sig_iter = key_iter->second.find(typeid(T(Args...)).name()); sig_iter != key_iter->second.end()) {
Что такое sig?

2021-03-31 14:37 UTC, efimov-evgeniy commented on include/cvs/common/factory.hpp
> +  template <typename FactoryFunction, typename ImplType>
Стоит добавить проверок на входные типы. Например, что FactoryFunction - callable.

2021-03-31 15:17 UTC, Aldrog requested changes

2021-03-31 15:17 UTC, Aldrog commented on CMakeLists.txt
> +  EXPORT_FILE_NAME ${CMAKE_CURRENT_BINARY_DIR}/export/cvs/common/${PROJECT_NAME_LOWER}export.hpp)
Если мы используем макросы экспорта, то логично было бы `-fvisibility=hidden` использовать.
```suggestion
generate_export_header(${PROJECT_NAME}
  EXPORT_FILE_NAME ${CMAKE_CURRENT_BINARY_DIR}/export/cvs/common/${PROJECT_NAME_LOWER}export.hpp)

set(CMAKE_CXX_VISIBILITY_PRESET hidden)
set(CMAKE_VISIBILITY_INLINES_HIDDEN 1)
```

2021-03-31 15:17 UTC, Aldrog commented on include/cvs/common/factory.hpp
> +  void registrate(const KeyType &key, std::function<FactoryFunction> fun) {
Я понимаю, что `register` зарезервировано, но использование несуществующих / архаичных слов мне не очень нравится. Можно `registerType` назвать, даже более наглядно будет.

2021-03-31 15:17 UTC, Aldrog commented on include/cvs/common/factory.hpp
> +  struct BaseHelper {
Лучше бы назвать `HelperBase` — это base для `Helper`, а не helper для base.

2021-03-31 15:17 UTC, Aldrog commented on include/cvs/common/factory.hpp
> +  using BaseHelperPtr = std::shared_ptr<BaseHelper>;
Тут вроде `unique_ptr` более уместен был бы.

2021-03-31 15:17 UTC, Aldrog commented on include/cvs/common/factory.hpp
> +  using Signatures = std::map<std::string, BaseHelperPtr>;
А зачем позволять несколько типов по одному ключу регистрировать? Просто на всякий случай?

2021-03-31 15:17 UTC, Aldrog commented on include/cvs/common/factory.hpp
> +  std::optional<T> create(const KeyType &key, Args &&... args) {
А тут точно `optional` нужен? У нас же T обычно является указателем, а указатели сами по себе семантику опциональности несут.

2021-03-31 15:17 UTC, Aldrog commented on include/cvs/common/factory.hpp
> +  std::optional<T> create(const KeyType &key, Args &&... args) {
Ну и смежный вопрос — не лучше ли сделать обязательным использование `unique_ptr` (заменить `T` на `unique_ptr<T>`) во всех функциях фабрики?

2021-03-31 15:17 UTC, Aldrog commented on include/cvs/common/factory.hpp
> +  bool registrateIf(const KeyType &key, std::function<FactoryFunction> fun) {
Предлагаю переименовать в `tryRegister` (по крайней мере по аналогии с `std::map::try_emplace` можно догадаться, что это такое), либо во что-то более длинное и явное.

2021-03-31 15:17 UTC, Aldrog commented on include/cvs/common/factory.hpp
> +        if (helper) {
Он же может быть `nullptr` только если `type_info::name` сгенерировался одинаковый для двух типов, зарегестрированных по одному ключу. Наверное, надо либо какую-то ошибку тогда выкидывать, либо вообще исключить возможность подобной ситуации, запретив регистрировать по одному ключу несколько типов.

2021-03-31 15:17 UTC, Aldrog commented on include/cvs/common/staticfactory.hpp
> +class CVSCOMMON_EXPORT StaticFactory {
А зачем два разных типа фабрики? Как их использовать предполагается?

2021-04-01 09:38 UTC, ssysoenko commented on include/cvs/common/factory.hpp
> +  using Signatures = std::map<std::string, BaseHelperPtr>;
Для копирования поведения StaticFactory. Там ключем являются и значение того, что передано как key, и сигнатура фабричной функции.

2021-04-01 09:41 UTC, ssysoenko commented on include/cvs/common/factory.hpp
> +  std::optional<T> create(const KeyType &key, Args &&... args) {
У нас не везде указатель. В пайплайне для имени ноды регистрируется функция возвращающая тип ноды (чтобы узнать тип без создания ноды). Можно и динамически создавать, но так вообще нет никаких ограничений, что не является прям недостатком в таком случае.
Возможно стоит отказаться от optional и перейти к исключениям. Ну или использовать шаблон expected.

2021-04-01 12:56 UTC, ssysoenko commented on include/cvs/common/staticfactory.hpp
> +class CVSCOMMON_EXPORT StaticFactory {
Статическую нельзя использовать с модулями. Т.к. инстанцирование происходит в модуле (при регистрации) и не подцепляется кодом, загружающим модуль. Для этого и написана еще фабрика которая все фабричные методы сохраняет в контейнер.
Ну а старую фабрику не выкидывать же. Пусть будет.

2021-04-01 12:58 UTC, ssysoenko commented on include/cvs/common/factory.hpp
> +    if (auto key_iter = factory_functions.find(key); key_iter != factory_functions.end()) {
Зачем? Конкретно этот кусок - типичное, что делается с контейнерами.

2021-04-01 13:03 UTC, ssysoenko commented on include/cvs/common/factory.hpp
> +    if (!isRegistered<FactoryFunction>(key)) {
Сейчас уже не вспомню кто конкретно, но какой-то дядька (типа Маерса) писал, что конструкции
`if()
  return;
бла бла бла`
это не очень хорошо. Мол можно выстрелить в ногу. Поэтому придерживаюсь правила, что если не большая вложенность - то лучше избегать упомянутых конструкций.

2021-04-01 13:49 UTC, ssysoenko commented on include/cvs/common/factory.hpp
> +  template <typename FactoryFunction, typename ImplType>
Может концептов дождаться? А то что-то нет желания городить этот шаблонный ад.

2021-04-01 13:53 UTC, ssysoenko commented on include/cvs/common/factory.hpp
> +  using BaseHelperPtr = std::shared_ptr<BaseHelper>;
В коде есть dynamic_pointer_cast. Если unique - придется манипулировать указателем.

2021-04-01 14:03 UTC, ssysoenko commented on include/cvs/common/factory.hpp
> +        if (helper) {
Вроде как имя не должно генерироваться одинаковым, в отличие от хеша...

2021-04-01 14:15 UTC, Aldrog commented on include/cvs/common/factory.hpp
> +  using BaseHelperPtr = std::shared_ptr<BaseHelper>;
Не вижу проблем с тем, чтобы сделать get и обычный `dynamic_cast`. В отличии от указания разделяемого владения там, где должно быть эксклюзивное.

2021-04-01 14:15 UTC, Aldrog commented on include/cvs/common/factory.hpp
> +        if (helper) {
Надо почитать доку gcc, может там даются такие гарантии, но по стандарту нет.

2021-04-01 14:16 UTC, Aldrog commented on include/cvs/common/factory.hpp
> +  template <typename FactoryFunction, typename ImplType>
Так в GCC 10 они уже есть.

2021-04-01 14:17 UTC, Aldrog commented on include/cvs/common/factory.hpp
> +    if (!isRegistered<FactoryFunction>(key)) {
Это не про C случайно было? В C++ это наоборот, хорошим паттерном обычно считается.

2021-04-01 14:34 UTC, ssysoenko commented on include/cvs/common/factory.hpp
> +    if (!isRegistered<FactoryFunction>(key)) {
Ну может у автора это было навеяно от C. Идея была такая: проверяются условия при которых нужно совершить какое-то действие, и если вдруг что-то было не учтено - действие не будет совершено и не изменится состояние. Что, предполагается, лучше чем менять состояние.

2021-04-01 14:36 UTC, ssysoenko commented on include/cvs/common/factory.hpp
> +    if (!isRegistered<FactoryFunction>(key)) {
Не то чтобы мне сильно принципиально, но давайте тогда проверим где написано что-то за или против такой записи.

2021-04-01 14:37 UTC, ssysoenko commented on include/cvs/common/factory.hpp
> +  template <typename FactoryFunction, typename ImplType>
И вот она беседа про версию смаке - но уже про гцц. :)

2021-04-01 14:40 UTC, ssysoenko commented on include/cvs/common/factory.hpp
> +  using BaseHelperPtr = std::shared_ptr<BaseHelper>;
Конфликт 2х практик:
- избегать использования указателей
- не использовать разделяемое владение там где эксклюзивное
В любом случае что-то нарушается. 
@efimov-evgeniy  тебе как больше нравится?

2021-04-01 14:51 UTC, ssysoenko commented on include/cvs/common/factory.hpp
> +        if (helper) {
Ну тут речь идет про сигнатуру функции. Если при генерации имени могут быть проигнорированы cv ref - то будет колизия. Т.е. это могут быть разные типы (2 разные функции но с одной сигнатурой, если не ошибка называть их типами), но тут мы вроде как не оперируем понятием типа, а важна нам сигнатруа. Хотя я теперь, кажись, запутался...

2021-04-01 16:18 UTC, Aldrog commented on include/cvs/common/factory.hpp
> +    if (!isRegistered<FactoryFunction>(key)) {
> Идея была такая: проверяются условия при которых нужно совершить какое-то действие, и если вдруг что-то было не учтено - действие не будет совершено и не изменится состояние.

В сценарии вида "A и B — ошибочные состояния, при них работать не надо" забытая проверка на A (или на B) даст абсолютно одинаковый результат при обоих подходах.

2021-04-01 16:38 UTC, Aldrog commented on include/cvs/common/factory.hpp
> +  using BaseHelperPtr = std::shared_ptr<BaseHelper>;
Избегать использования указателей — это какой-то нонсенс. Обычно за правило берётся "не выражать владение чистыми указателями", то есть не использовать new и delete, избегать указателей среди членов класса. Ну и арифметики на указателях избегают.

Вот, например, в C++ Core Guidelines хорошо обоснованное [правило](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#f7-for-general-use-take-t-or-t-arguments-rather-than-smart-pointers), по которому надо **предпочитать** чистые указатели умным в аргументах функций. И мой опыт поддтверждает, что его несоблюдение может к большим проблемам привести.

2021-04-01 16:45 UTC, Aldrog commented on include/cvs/common/factory.hpp
> +        if (helper) {
А почему бы не сделать так?
```cpp
using Signatures = std::unordered_map<std::type_info, BaseHelperPtr>;
```
Тогда вроде всё однозначно даже с точки зрения стандарта.

2021-04-01 16:53 UTC, Aldrog commented on include/cvs/common/staticfactory.hpp
> +class CVSCOMMON_EXPORT StaticFactory {
Git и так всё помнит :)
А использовать их совместно всё равно ведь не выйдет, так что я бы усомнился в целесообразности таскания старой версии.

2021-04-01 16:55 UTC, Aldrog commented on include/cvs/common/staticfactory.hpp
> +class CVSCOMMON_EXPORT StaticFactory {
Разве что ты знаешь о каком-то сценарии в другом проекте, для которого она лучше подходит.

2021-04-05 07:39 UTC, ssysoenko commented on include/cvs/common/factory.hpp
> +  using BaseHelperPtr = std::shared_ptr<BaseHelper>;
Как я понял там в первую очередь про то, чтобы не ограничивать круг пользователей только теми, у кого умные указатели. И мол для функции не так критично манипулировать просто указателем.
Не вижу никакого нонсенса в максиме "использовать только умные указатели". Через них то какраз понятно кто владеет объектом, кто его держит, а кто нет.
В общем случае конечно крайне плохо вынуждать всех использовать умные указатели (например когда пишешь какой-нить буст). Но в рамках поуже - вполне себе допустимо.
Как писал выше - красивого решения тут нет. Наверно переписать на unique будет правильнее т.к. это семантически понятнее, а манипулирование указетелм - один эпизот внутри одной функции (которую и так надо будет мьютексами защищать).

2021-04-05 07:46 UTC, ssysoenko commented on include/cvs/common/factory.hpp
> +        if (helper) {
А это я просто тупанул :)

2021-04-05 07:52 UTC, ssysoenko commented on include/cvs/common/factory.hpp
> +        if (helper) {
А нет. Не тупанул. Из `std::type_info` хеш не сделать. А тот хеш который в нем есть - использовать нельзя.

2021-04-05 08:07 UTC, ssysoenko commented on include/cvs/common/staticfactory.hpp
> +class CVSCOMMON_EXPORT StaticFactory {
Ну это же библиотека. В рамках библитеки оставить что-то это не проблема.

2021-04-05 08:13 UTC, Aldrog commented on include/cvs/common/factory.hpp
> +  using BaseHelperPtr = std::shared_ptr<BaseHelper>;
> про то, чтобы не ограничивать круг пользователей только теми, у кого умные указатели

Больше даже про то, чтобы функция не заставляла вызывающую сторону использовать конкретный тип умного указателя.
В целом во многих случаях можно использовать какой-нибудь `std::optional<std::reference_wrapper<T>>`, но это неэффективно, жутко громоздко, а преимуществ я что-то вообще никаких не вижу.

2021-04-05 08:14 UTC, Aldrog commented on include/cvs/common/factory.hpp
> +        if (helper) {
Почему нельзя? Что-то мешает его использовать в специализации `std::hash`?

2021-04-05 08:17 UTC, Aldrog commented on include/cvs/common/staticfactory.hpp
> +class CVSCOMMON_EXPORT StaticFactory {
Ок, согласен.

2021-04-05 09:50 UTC, efimov-evgeniy commented on include/cvs/common/factory.hpp
> +  template <typename FactoryFunction, typename ImplType>
> А то что-то нет желания городить этот шаблонный ад

Почему ад? Добавить просто пару static_assert с проверками.

2021-04-05 09:53 UTC, efimov-evgeniy commented on include/cvs/common/factory.hpp
> +    if (auto key_iter = factory_functions.find(key); key_iter != factory_functions.end()) {
Имхо типично итератор проверяется на равенство .end(), и в случае положительного результата вызывается return.
Ну и объявление в if - не очень практичная штука. Ожидаешь условие, а не создание новый переменных.

2021-04-06 07:51 UTC, ssysoenko commented on include/cvs/common/factory.hpp
> +        if (helper) {
Ну вот если написать так:
`using Signatures = std::unordered_map<std::type_info, HelperBasePtr>;`
То не работает. Там же вроде как std::hash по умолчанию используется? Надо специализацию делать, видимо

2021-04-06 08:22 UTC, Aldrog commented on include/cvs/common/factory.hpp
> +        if (helper) {
Ну да, должно быть что-то вроде

```cpp
namespace std {
template<> struct hash<type_info> {
  std::size_t operator()(const type_info &ti) const noexcept {
    return ti.hash_code();
  }
};
}
```

2021-04-06 16:10 UTC, ssysoenko commented on include/cvs/common/factory.hpp
> +    if (auto key_iter = factory_functions.find(key); key_iter != factory_functions.end()) {
этож одна из фишек обновленного стандарта так писать. Как такое можно не ожидать? :)

2021-04-06 16:12 UTC, ssysoenko commented on include/cvs/common/factory.hpp
> +  template <typename FactoryFunction, typename ImplType>
Ты тот же эфект толучишь от аргумента который 

`std::function<FactoryFunction>`

2021-04-06 16:13 UTC, ssysoenko commented on include/cvs/common/factory.hpp
> +        if (helper) {
Ну а hash_code - [не уникален](https://en.cppreference.com/w/cpp/types/type_info/hash_code).

2021-04-06 16:26 UTC, Aldrog commented on include/cvs/common/factory.hpp
> +        if (helper) {
А `std::hash<long double>` или `std::hash<string>` уникальны? Они и не должны быть уникальными по определению.

Вообще, похоже, и специализацию писать не обязательно, нашёл в стандартной библиотеке [type_index](https://en.cppreference.com/w/cpp/types/type_index), обёртку над `type_info` для которой `std::hash` уже специализирован.

2021-04-06 23:47 UTC, efimov-evgeniy commented on include/cvs/common/factory.hpp
> +    if (auto key_iter = factory_functions.find(key); key_iter != factory_functions.end()) {
Ну, нововведение, может, и полезное в отдельных ситуациях, но имхо в большинстве случаев сомнительное. Какая-то неуклюжая попытка запихнуть в скоуп if'а объявление переменной. После раста с его `if let` и `match` выглядит довольно убого.
Я не наставиваю, но мне кажется, что в небольшом скоупе проще понять классический вариант.

2021-04-06 23:51 UTC, efimov-evgeniy commented on include/cvs/common/factory.hpp
> +  template <typename FactoryFunction, typename ImplType>
Я боюсь, что выводимая ошибка будет малопонятной. Выяснять откуда она прилетела может быть не самым приятным занятием.

2021-04-07 09:31 UTC, ssysoenko commented on include/cvs/common/factory.hpp
> +  template <typename FactoryFunction, typename ImplType>
Я вот не уверен, что дойдет до статик асерта т.к. грохнется на инстанцировании std::function

2021-04-13 09:04 UTC, ssysoenko commented on include/cvs/common/factory.hpp
> +  std::optional<T> create(const KeyType &key, Args &&... args) {
Предлагаю пока оставить optional и позже завязать на expected. Это позволит прокидывать ошибки из фабричных функций в место вызова метода фабрики.

2021-04-13 10:22 UTC, efimov-evgeniy requested changes

2021-04-13 10:22 UTC, efimov-evgeniy commented on include/cvs/common/staticfactory.hpp
> +    if (auto iter = creator_map.find(key); iter != creator_map.end())
Здесь тоже можно поправить условие.

2021-04-13 10:22 UTC, efimov-evgeniy commented on src/config.cpp
> +  if (!children.empty())
И здесь

2021-04-13 10:44 UTC, ssysoenko commented on src/config.cpp
> +  if (!children.empty())
А тут то что?

2021-04-13 16:51 UTC, efimov-evgeniy commented on src/config.cpp
> +  if (!children.empty())
Ну ты везде сделал так, что финальный return возвращает валидный результат, и это хорошо. Эта функция выбивается из общей картины.

2021-04-13 16:57 UTC, Aldrog requested changes

2021-04-13 16:57 UTC, Aldrog commented on include/cvs/common/factory.hpp
> +};  // namespace cvs::common
Это не закрытие namespace
```suggestion
};
```

2021-04-14 05:22 UTC, ssysoenko commented on src/config.cpp
> +  if (!children.empty())
Если не секрет, чем хорошо?

2021-04-14 05:24 UTC, ssysoenko commented on src/config.cpp
> +  return std::nullopt;
```suggestion
  if (children.empty())
    return std::nullopt;

  return children.front();
```

2021-04-14 08:33 UTC, Aldrog approved these changes

2021-04-14 09:53 UTC, efimov-evgeniy commented on src/config.cpp
> +  if (!children.empty())
Например, тем, что по последнему `return` видно что возвращает функция. И тип, и суть обычно. А `return std::nullopt` ни о чём не говорит. Иначе надо вглядываться в код и искать "смысловой" возврат.

2021-04-14 19:08 UTC, efimov-evgeniy approved these changes

2021-04-15 08:05 UTC, ssysoenko commented on src/config.cpp
> +  if (!children.empty())
Ну дык по последнему return нельзя судить о возвращаемом функцией. Это всего один из вариантов возвращаемого. Выше есть условия при которых может быть возвращено что угодно. Надо либо четче сформулировать рекомендации по офрмлению функций, либо забить болт на это.

2021-04-15 08:08 UTC, merged