Config value vector of string specialization
servacc/CVSCommon pull request #8
Opened 2021-07-02 00:27 UTC by efimov-evgeniy

Добавил специализацию `ConfigValue` для `std::vector<std::string>`

2021-07-04 08:59 UTC, ssysoenko approved these changes

2021-07-05 09:28 UTC, Aldrog commented
А нельзя это обобщить до `std::vector<T>`, где T — любой поддерживаемый парсером тип?

2021-07-08 16:46 UTC, Aldrog requested changes

2021-07-08 16:46 UTC, Aldrog commented on include/cvs/common/configbase.hpp
> +        result[i] = boost::lexical_cast<std::string>(strings->at(i));
Здесь явно должен был быть `typename Subtype::value_type`, а не `std::string`.

2021-07-08 16:46 UTC, Aldrog commented on include/cvs/common/configbase.hpp
> +    auto strings = get_value_from_ptree<std::vector<std::string>>(source, name);
На мой взгляд было бы лучше перенести сюда реализацию для `std::vector<std::string>`, заменив в ней `std::string` на `Subtype::value_type`. Тогда и в отдельной специализации необходимость отпадёт, и не будет странного чтения в вектор строк с последующей конвертацией.

2021-07-08 19:16 UTC, Aldrog commented on include/cvs/common/configbase.hpp
> +        auto value_optional = item.second.template get_value_optional<Subtype::value_type>();
Без `typename` компилятор не понимает, что `Subtype::value_type` это тип. 

```suggestion
        auto value_optional = item.second.template get_value_optional<typename Subtype::value_type>();
```
Или можно через `using` ему альяс объявить, там контекст однозначный.
```cpp
using ValueType = Subtype::value_type;
...
get_value_optional<ValueType>();
```

2021-07-09 08:28 UTC, Aldrog approved these changes

2021-07-12 00:00 UTC, merged